### ISSUE TITLE
didn't succeed in ubuntu 14.04 when run /bin/bash ..

### ISSUE THREAD

**Issue by bboalimoe** [TykTechnologies/tyk-dashboard-docker#1]
don't know why ..but i fix it by entering the container ..~~

**Comment by lonelycode** [comment]
Did you use master branch? Master branch is totally unstable. This repo is for docker hub automarted build

Use one of the versioned branches - https://github.com/lonelycode/tyk-dashboard-docker/tree/version/v0.9.4.1 is latest currently. (make sure to read the README, by default assumes you are linking redis and mongo)

Or use the Automated build on Dockerhub: https://registry.hub.docker.com/u/tykio/tyk-dashboard/ (latest tag is up to date)
