### ISSUE TITLE
Issue with bootstrap script

### ISSUE THREAD

**Issue by alexraju91** [TykTechnologies/tyk-dashboard-docker#3]
In [bootstrap.sh](https://raw.githubusercontent.com/lonelycode/tyk-dashboard-docker/version/v1.1/bootstrap.sh), 

`USER_DATA=$(curl --silent --header "admin-auth: 12345" --header "Content-Type:application/json" --data '{"first_name": "John","last_name": "Smith","email_address": "'$RANDOM_USER'@default.com","password":"'$PASS'", "active": true,"org_id": "'$ORGID'"}' http://$LOCALIP:3000/admin/users 2>&1)`

is giving me the following response:

`{"Status":"OK","Message":"User created","Meta":""}`

The message information is simply 'User created' text and we are using this as authorization header value in below request.

```
USER_CODE=$(echo $USER_DATA | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["Message"]')
echo "USER AUTH: $USER_CODE" 

USER_LIST=$(curl --silent --header "authorization: $USER_CODE" http://$LOCALIP:3000/api/users 2>&1)
```

And no wonder, its giving me following error.

`{"Status":"Error","Message":"Not authorised","Meta":""}`

Please help me to create tyk users for logging to dashboard.

**Comment by lonelycode** [comment]
Really? Calling that endpoint on my system returns a full user object and their access key.

Are you calling he _admin_ endpoint (`/admin/users`) or the within-org user creation endpoint (`/api/users`), because that endpoint returns the output you describe while the admin endpoint returns the meta-data you need.

**Comment by alexraju91** [comment]
Its the admin endpoint. 

![issue](https://cloud.githubusercontent.com/assets/11927055/15749762/2ea88f14-2901-11e6-8a36-a173674ddde0.png)

**Comment by lonelycode** [comment]
Your curl command breaks the string in half, replace '$PASS' with a test password, those single quotes might be causing issues

**Comment by alexraju91** [comment]
@lonelycode I tried with a test password like below

`curl --silent --header "admin-auth: 12345" --header "Content-Type:application/json" --data '{"first_name": "John","last_name": "Smith","email_address": "alex@default.com","password":"test", "active": true,"org_id": "575002eb60a492000100000a"}' http://1.1.1.1:3000/admin/users 2>&1
`

Still the same response
`{"Status":"OK","Message":"User created","Meta":""}`

**Comment by lonelycode** [comment]
Do these users show up in your dashboard?

Secondly, does the bootstrap script work on its own?

**Comment by alexraju91** [comment]
@lonelycode I don't have any users to login to the dashboard. That's why I'm running this script. I got this issue when running the whole script on its own and when running each lines individually.

**Comment by lonelycode** [comment]
Hang on, I think I know the problem. Which branch are you using?

**Comment by lonelycode** [comment]
Also, you've got mongo and everything else hooked up? With a. License?

**Comment by alexraju91** [comment]
I'm using gateway v2.1.0.2 with dashboard v1.1. 
I executed bootscript wholly and each lines separately. Both did't work. 

I doubt if this issue is related to https://github.com/lonelycode/tyk-gateway-docker/issues/1 .

Thank you for the help.

**Comment by alexraju91** [comment]
Also, the expected response to the API is 

```
{
    "Status": "OK",
    "Message": "User created",
    "Meta": ""
}
```

as per the official doc https://tyk.io/docs/tyk-dashboard-v1-0/dashboard-api/admin-api-users/

**Comment by lonelycode** [comment]
That documentation is a little out of date - I assure you that it isn't the case.

**Comment by lonelycode** [comment]
Can I suggest you try the docker QuickStart? It's self contained, makes use of the same APIs and uses these containers as its baseline.

Not a production install, but it'll give you a good place to start

**Comment by alexraju91** [comment]
@lonelycode I'm setting up Tyk in Marathon. So, you see I can't use the docker compose as it is.

**Comment by alexraju91** [comment]
@lonelycode Thank you. It worked. Able to access the dashboard now.
